use_frameworks!
source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'

target 'hxbbTest_Example' do
#  pod 'hxbbTest', :path => '../'
  pod 'hxbbTest', '~> 0.2.0'

  target 'hxbbTest_Tests' do
    inherit! :search_paths

    
  end
end
